# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
#
enable_audio_bell no
shell zsh
editor nvim

# Fonts
font_size 13.0
font_family     JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto


tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_align center

window_margin_width 5
window_padding_width 0

clear_all_shortcuts yes
# Kitty mod
kitty_mod alt

# Reload kitty.conf

map kitty_mod+f5 load_config_file


# Copy and paste
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard

# Scroll
map kitty_mod+k scroll_line_up
map kitty_mod+j scroll_line_down
map kitty_mod+z scroll_to_prompt -1 
map kitty_mod+x scroll_to_prompt 1 

# Windows management

map kitty_mod+enter new_window
map kitty_mod+w close_window
map kitty_mod+n next_window
map kitty_mod+p previous_window
map kitty_mod+i move_window_forward
map kitty_mod+o move_window_backward
map kitty_mod+a new_window_with_cwd

# Tab management
map kitty_mod+t new_tab
map kitty_mod+q close_tab
map kitty_mod+l next_tab
map ctrl+tab next_tab
map kitty_mod+h previous_tab
map ctrl+shift+tab previous_tab
map kitty_mod+. move_tab_forward
map kitty_mod+, move_tab_backward
map kitty_mod+r set_tab_title

# Layout management
map kitty_mod+m next_layout

# Font Sizes
map kitty_mod+equal change_font_size all +1.0
map kitty_mod+plus  change_font_size all +1.0

map kitty_mod+minus  change_font_size all -1.0



# Miscelaneous
