# hyprtoolkit, es utlizado para realizar la cutomizacion de colores de cualquier aplicacion que corra nativamente en wayland junto con hyprland

background = 0xF2060C18
base = 0xF20B1222
text = 0xFFE9F4FF
alternate_base = 0xF213213F
bright_text = 0xFFFFFFFF
accent = 0xFF7AD9FF
accent_secondary = 0xFF78A9FF
h1_size = 20
h2_size = 16
h3_size = 14
font_size = 13
small_font_size = 11
font_family = IosevkaTerm Nerd Font Mono
font_family_monospace = IosevkaTerm Nerd Font Mono
rounding_large = 18
rounding_small = 12
